Change back
Signed-off-by: Ian Hoang <ianhoang16@gmail.com>

diff --git a/.github/workflows/workload-format-checker.yml b/.github/workflows/workload-format-checker.yml
--- a/.github/workflows/workload-format-checker.yml
+++ b/.github/workflows/workload-format-checker.yml
@@ -43,9 +43,21 @@ jobs:
       - name: Run J2lint on all JSON files in a branch
         if: github.event_name == 'workflow_dispatch'
         run: |
-          chmod +x "$GITHUB_WORKSPACE/.github/j2_format_checker.sh"
-          ./$GITHUB_WORKSPACE/.github/j2_format_checker.sh "$GITHUB_WORKSPACE"
+          # Filter out indention errors that are prevalent throughout repository
+          j2lint $GITHUB_WORKSPACE --extensions json --json | jq '.ERRORS |= map(select(.severity == "HIGH" and (.message | contains("Bad Indentation") | not)))' > j2_format_check_output.json
 
+          # See ERRORS and WARNINGS
+          cat j2_format_check_output.json
+
+          # Check high severity count. We only fail on high severity counts that are not idention issues
+          high_severity_count=$(jq '.ERRORS | length' j2_format_check_output.json)
+          if [ "$high_severity_count" -gt 0 ]; then
+          echo "Found $high_severity_count high severity issues. Failing check. Please address the Jinja2 formatting issues with the above files"
+          exit 1
+          else
+          echo "No high severity issues found. Passing check :)"
+          exit 0
+          fi
 
 
 
